site_name: Cancercelllines Documentation
site_description: 'Documentation for the Cancercelllines genomics resource'
site_author: Michael Baudis
copyright: '&copy; Copyright 2022, Michael Baudis, Rahel Paloots and progenetix.org'
repo_name: 'cancercelllines-web'
repo_url: https://github.com/progenetix/cancercelllines-web

###############################################################################

nav:
  - Documentation Home: index
  - News & Changes: news
  - Literature data: literature-data
  - Cancercelllines Data &#8599;: http://cancercelllines.org
  - Progenetix Data &#8599;: http://progenetix.org
  - Baudisgroup @ UZH &#8599;: http://info.baudisgroup.org

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid   
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - mdx_gh_links:
      user: progenetix
      repo: cancercelllines-web
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

###############################################################################

theme:
  name: material
  # palette:
  #   primary: deep orange
  favicon: img/site-logo-topright.png
  logo: img/site-logo-topright.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - toc.integrate
  custom_dir: extra
      
plugins:
    - search
    - macros
    - mermaid2

extra:
  excerpt_separator: <!--more-->
  blog_list_length: 100
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://genomic.social/@progenetix
    - icon: fontawesome/brands/github 
      link: https://github.com/progenetix
extra_css:
  - css/theme_overrides.css
extra_javascript:
  # - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    
