---
note: ""
label: ""
description: ""
parameters:
  datasetIds:
    defaultValue: ["cellz"]
  assemblyId:
    isHidden: true
  referenceName:
    placeholder: "9"
  start:
    placeholder: "19000001-21975098"
  end:
    placeholder: "21967753-24000000"
  variantType:
    placeholder: "EFO:0030067"
  alternateBases:
    placeholder: ""
    isHidden: false
  referenceBases:
    placeholder: ""
    isHidden: false
  accessid:
    isHidden: true
  filterPrecision:
    isHidden: true
  materialtype:
    isHidden: true
  clinicalClasses:
    isHidden: true
examples:
  - label: "HLF Cell Line"
    note: "Instances of HLF and daughter cell lines, searched by Cellosaurusid"
    description: >-
      The query retrieves all instances of HLF and derived cell lines using
      the "cellosaurus:CVCL_2947" identifier. HLF has a set of annotated
      variants including a Li-Fraumeni TP53 mutation.
    parameters:
      variantType:
        defaultValue: ""
        isHidden: true
      referenceName:
        isHidden: true
      geneId:
        isHidden: true
      variantMinLength:
        isHidden: true
      variantMaxLength:
        isHidden: true
      clinicalClasses:
        isHidden: true
      start:
        isHidden: true
      end:
        isHidden: true
      alternateBases:
        isHidden: true
      referenceBases:
        isHidden: true
      bioontology:
        isHidden: true
      cohorts:
        isHidden: true
      sex:
        isHidden: true
      materialtype:
        isHidden: true
      freeFilters:
        isHidden: true
      filterLogic:
        isHidden: true
      accessid:
        isHidden: true
      geoCity:
        isHidden: true
      referenceid:
        defaultValue: ["cellosaurus:CVCL_2947"]
  - label: "K-562 Cell Line"
    note: "Instances of K-562 and daughter cell lines, searched by Cellosaurus id"
    description: >-
      The query retrieves all instances of K-562 and derived cell lines using
      the "cellosaurus:CVCL_0004" identifier. This is an example for a pure
      "non-variant" filter query.
    parameters:
      variantType:
        defaultValue: ""
        isHidden: true
      referenceName:
        isHidden: true
      geneId:
        isHidden: true
      variantMinLength:
        isHidden: true
      variantMaxLength:
        isHidden: true
      clinicalClasses:
        isHidden: true
      start:
        isHidden: true
      end:
        isHidden: true
      alternateBases:
        isHidden: true
      referenceBases:
        isHidden: true
      bioontology:
        isHidden: true
      cohorts:
        isHidden: true
      sex:
        isHidden: true
      materialtype:
        isHidden: true
      freeFilters:
        isHidden: true
      filterLogic:
        isHidden: true
      accessid:
        isHidden: true
      geoCity:
        isHidden: true
      referenceid:
        defaultValue: ["cellosaurus:CVCL_0004"]
  - label: "CDKN2A Deletion Example in CL"
    note: "Example for focal CDKN2A deletion matches."
    description: |
      This example shows the query for CNV deletion variants overlapping the CDKN2A gene's coding region with at least a single base, but limited to "highly focal" hits (here i.e. <= ~1Mbp in size). The query can be modified e.g. through changing the position parameters or diagnosis.
    parameters:
      referenceName:
        defaultValue: "refseq:NC_000009.12"
      start:
        defaultValue: "21500001-21975098"
      end:
        defaultValue: "21967753-22500000"
      variantType:
        defaultValue: "EFO:0030067"
      variantMinLength:
        isHidden: true
      variantMaxLength:
        isHidden: true
      bioontology:
        defaultValue: ["NCIT:C3058"]
      accessid:
        isHidden: true
      geoCity:
        isHidden: true
  - label: "MYC Duplication in CL"
    note: "Example for focal MYC Duplications."
    description: |
      The example parameters will select samples with a continuous, focal duplication
      of the complete MYC coding region.
    parameters:
      referenceName:
        defaultValue: "refseq:NC_000008.11"
      start:
        defaultValue: "124000000-127736593"
      end:
        defaultValue: "127740957-130000000"
      variantType:
        defaultValue: "EFO:0030070"
      variantMinLength:
        isHidden: true
      variantMaxLength:
        isHidden: true
      accessid:
        isHidden: true
      geoCity:
        isHidden: true
  - label: "TP53 Del. in Cell Lines"
    note: "Example for TP53 deletion"
    description: >-
      Query example for an "any overlap", focal deletion in TP53.
    parameters:
      referenceName:
        defaultValue: "refseq:NC_000017.11"
      start:
        defaultValue: "5000000-7676592"
      end:
        defaultValue: "7669608-10000000"
      variantType:
        defaultValue: "EFO:0030067"
      accessid:
        isHidden: true
      geoCity:
        isHidden: true

    
    
